#!/bin/bash

#bridgestor3on.sh
#Developer Leandro Santos - https://github.com/leandroibov

echo "bridgestor3off.sh";
echo;
#*****
echo "Seaching tor user in the system..."
if command -v pacman > /dev/null; then
  TOR_USER=$(getent passwd tor | cut -d: -f1)
elif command -v apt > /dev/null; then
  TOR_USER=$(getent passwd debian-tor | cut -d: -f1)
elif command -v dnf > /dev/null; then
  TOR_USER=$(getent passwd toranon | cut -d: -f1)
else
    echo "Unknown distro!"
  exit
fi

if [ -n "$TOR_USER" ]; then
   echo "The Tor user on the system is: $TOR_USER"
else
  echo "Tor user not found. Please install the Tor Hidden Service."
  echo "https://support.torproject.org/apt/"

fi
#*****


echo;
echo "Removing bridges for torrc.3 file... "$TOR_USER"";
sudo rm -rf /var/tmp/torrc.3;
sudo cat > /var/tmp/torrc.3 << EOF
SocksPort 9062
ControlPort 9063
DataDirectory /var/tmp/tor3 
EOF

echo;
echo "Verifing torrc.3 file:";
cat /var/tmp/torrc.3;
echo;

sudo echo "Restarting: Disabling the tor instance 3"
sudo echo "sudo systemctl disable tor3.service;";
sudo systemctl disable tor3.service;
sudo echo "Stopping the tor instance 3"
sudo echo "sudo systemctl stop tor3.service;";
sudo systemctl stop tor3.service;
sudo echo "Restarting the tor instance 3"
sudo echo "sudo systemctl enable tor3.service;";
sudo systemctl enable tor3.service;
sudo echo "";
sudo echo "sudo systemctl start tor3.service;"
sudo systemctl start tor3.service;
sudo echo "sudo systemctl restart tor3.service;"
sudo systemctl restart tor3.service;
sudo echo "";
sudo echo "sudo systemctl is-active tor3.service;";
sudo systemctl is-active tor3.service;
sudo echo "sudo systemctl status tor3.service;";
sudo systemctl status tor3.service;
sudo echo "";

