#!/bin/bash

#bridgestor4on.sh
#Developer Leandro Santos - https://github.com/leandroibov
echo;
echo "bridgestor4on.sh";
echo "You need obfs4proxy to run bridges - links below:";
echo "https://packages.debian.org/buster/amd64/obfs4proxy/download";
echo "https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/lyrebird";
echo "sudo apt-get install obfs4proxy";
echo;
#*****
echo "Seaching tor user in the system..."
if command -v pacman > /dev/null; then
  TOR_USER=$(getent passwd tor | cut -d: -f1)
elif command -v apt > /dev/null; then
  TOR_USER=$(getent passwd debian-tor | cut -d: -f1)
elif command -v dnf > /dev/null; then
  TOR_USER=$(getent passwd toranon | cut -d: -f1)
else
    echo "Unknown distro!"
  exit
fi

if [ -n "$TOR_USER" ]; then
   echo "The Tor user on the system is: $TOR_USER"
else
  echo "Tor user not found. Please install the Tor Hidden Service."
  echo "https://support.torproject.org/apt/"

fi
#*****


echo "";
echo "Copy the Bridge as below in the terminal...";
echo "obfs4 89.10.110.191:7644 7EC4CE9AB0640544C77FCF461C85E50A9E07F506 cert=i9s54eikMKz4BiU/yYyFpJaBfGm/9xvNf97dnkI6iPg4Ls5TRoyOwhaIQprLgPruBf/zYA iat-mode=4";
echo;
echo "Get bridges obfs4 in https://bridges.torproject.org/bridges";
echo "--------------------------------------------------------------";
read -rp "Enter the obfs4 Bridge you want to register in torrc.4:" bridge

echo "--------------------------------------------------------------";
echo "your bridge is: $bridge"
echo "--------------------------------------------------------------";
echo "";

echo;
echo "Adding bridges for torrc.4 file... "$TOR_USER"";
sudo rm -rf /var/tmp/torrc.4;
sudo cat > /var/tmp/torrc.4 << EOF
SocksPort 9064
ControlPort 9065
DataDirectory /var/tmp/tor4 

UseBridges 1
ClientTransportPlugin obfs4 exec /usr/bin/obfs4proxy managed
Bridge "$bridge"
EOF
echo;
sudo mkdir /var/tmp/tor4;
sudo chown "$TOR_USER":"$TOR_USER" /var/tmp/tor4;
sudo chown "$TOR_USER":"$TOR_USER" /var/tmp/torrc.4;



echo "Verifing torrc.4 file:";
cat /var/tmp/torrc.4;
echo;

sudo echo "Restarting: Disabling the tor instance 4"
sudo echo "sudo systemctl disable tor4.service;";
sudo systemctl disable tor4.service;
sudo echo "Stopping the tor instance 4"
sudo echo "sudo systemctl stop tor4.service;";
sudo systemctl stop tor4.service;
sudo echo "Restarting the tor instance 4"
sudo echo "sudo systemctl enable tor4.service;";
sudo systemctl enable tor4.service;
sudo echo "";
sudo echo "sudo systemctl start tor4.service;"
sudo systemctl start tor4.service;
sudo echo "sudo systemctl restart tor4.service;"
sudo systemctl restart tor4.service;
sudo echo "";
sudo echo "sudo systemctl is-active tor4.service;";
sudo systemctl is-active tor4.service;
sudo echo "sudo systemctl status tor4.service;";
sudo systemctl status tor4.service;
sudo echo "";
sudo echo "Use checkbridges to verify bridge connection status...";
sudo echo "";

echo;


