#!/bin/bash

#bridgestor1on.sh
#Developer Leandro Santos - https://github.com/leandroibov
echo;
echo "bridgestor1on.sh";
echo "You need obfs4proxy to run bridges - links below:";
echo "https://packages.debian.org/buster/amd64/obfs4proxy/download";
echo "https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/lyrebird";
echo "sudo apt-get install obfs4proxy";
echo;



echo "";
echo "Copy the Bridge as below in the terminal...";
echo "obfs4 89.10.110.191:7624 7EC3CE9AB0640524C77FCF361C85E50A9E07F506 cert=i9s53eikMKz4BiU/yYyFpJaBfGm/9xvNf97dnkI6iPg3Ls5TRoyOwhaIQprLgPruBf/zYA iat-mode=2";
echo;
echo "Get bridges obfs4 in https://bridges.torproject.org/bridges";
echo "--------------------------------------------------------------";
read -rp "Enter the obfs4 Bridge you want to register in torrc:" bridge

echo "--------------------------------------------------------------";
echo "your bridge is: $bridge"
echo "--------------------------------------------------------------";
echo "";

echo;
echo "Adding bridges for torrc file...";
echo "Backing up torrc original...";
echo "sudo cp -r /etc/tor/torrc /etc/tor/torrc1.bak";
sudo cp -r /etc/tor/torrc /etc/tor/torrc1.bak
sudo cat > /etc/tor/torrc << EOF
SocksPort 9050
ControlPort 9051

UseBridges 1
ClientTransportPlugin obfs4 exec /usr/bin/obfs4proxy managed
Bridge "$bridge"
EOF
echo;
#original tor do not need it...
#sudo mkdir /var/tmp/tor1;
#sudo chown "$TOR_USER":"$TOR_USER" /var/tmp/tor1;




echo "Verifing torrc file:";
cat /etc/tor/torrc;
echo;

sudo echo "Restarting: Disabling the tor instance 1"
sudo echo "sudo systemctl disable tor.service;";
sudo systemctl disable tor.service;
sudo echo "Stopping the tor instance 1"
sudo echo "sudo systemctl stop tor.service;";
sudo systemctl stop tor.service;
sudo echo "Restarting the tor instance 1"
sudo echo "sudo systemctl enable tor.service;";
sudo systemctl enable tor.service;
sudo echo "";
sudo echo "sudo systemctl start tor.service;"
sudo systemctl start tor.service;
sudo echo "sudo systemctl restart tor.service;"
sudo systemctl restart tor.service;
sudo echo "";
sudo echo "sudo systemctl is-active tor.service;";
sudo systemctl is-active tor.service;
sudo echo "sudo systemctl status tor.service;";
sudo systemctl status tor.service;
sudo echo "";
sudo echo "Use checkbridges to verify bridge connection status...";
sudo echo "";

echo;


