#!/bin/bash
##############Script################################
#status-tor-daemon2-service


echo;
#Certifique que o tor serviço está rodando;
echo "Certifique que o tor serviço está instalado e rodando.";


#Status tor instance 2
echo "sudo systemctl status tor.service;";
sudo systemctl status tor.service;

